[package]
name = "lp-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
good_lp = {version = "1.4.0", features = ["highs"], default-features = false}
